<!DOCTYPE html>
<?php
/**
 * @var $content
 */
?>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MPT View</title>
</head>
<body>
    <?php echo getMicroDate(); ?>
    <?php echo $content ?? '<h3>content is null</h3>'; ?>
</body>
</html>